# Not detected by the NER

patterns = [
    {"label": "PERSON", "pattern": "Professor McGonagall"},
    {"label": "PERSON", "pattern": "Uncle Vernon"},
    {"label": "PERSON", "pattern": "Uncle Vernon's"},
    {"label": "PERSON", "pattern": "Aunt Petunia"},
    {"label": "PERSON", "pattern": "Vernon"},
    {"label": "PERSON", "pattern": "Dudley's"},
    {"label": "PERSON", "pattern": "Auntie Marge's"}
]

# ---
# Proper nouns cleaning

# Credits to Martin, D. P.
# From http://dpmartin42.github.io/posts/wizard-network
all_real_names = {
	"Hannah Abbott": ["Abbott", "Hannah"],
	"Irma Pince": ["Pince"],
	"Poppy Pomfrey": ["Pomfrey", "Pomftey"],
	"James Potter": ["James", "Mr. Potter"],
	"Harry Potter": ["Harry", "Potter", "Happy Birthday Harry", "Mr. H. Potter", "Mr. Harry Potter", "The Harry Potter"],
	"Lily Potter": ["Lily", "Lily an'", "Mrs. Potter"],
	"Quirinus Quirrell": ["Quirrell", "Quirtell"],
	"Millicent Bulstrode": ["Bulstrode"],
	"Gregory Goyle": ["Goyle"],
	"Hermione Granger": ["Gran", "Granger", "Hermione", "Hermlone", "Miss Granger", "Miss Granger's"],
	"Sirius Black": ["Sirius"],
	"Gellert Grindelwald": ["Grindelwald"],
	"Rubeus Hagrid": ["Hagrid"],
	"Helga Hufflepuff": ["Hufflepuff", "Hufflepuffis"],
	"Angelina Johnson": ["Angelina", "Chaser Angelina Johnson", "Johnson"],
	"Lee Jordan": ["Jordan", "Lee", "Lee Jordan's"],
	"Neville Longbottom": ["Mr. Longbottom", "Mr. Neville Longbottom", "Neville"],
	"Susan Bones": ["Susan"],
	"Draco Malfoy": ["Malfoy", "Mr. Malfoy"],
	"Minerva McGonagall": ["McGonagall", "McGonagall Harry", "Professor McGonagall"],
	"Terry Boot": ["Terry"],
	"Garrick Ollivander": ["Mr. Ollivander"],
	"Bettie Bott": ["Bettie", "Bettie Bott's"],
	"Malfoys Family": ["Malfoys", "The Malfoys"],
	"Auntie Marge": ["Marge"],
	"Piers Polkiss": ["Piers"],
	"Potter Family": ["Potters", "The Potters"],
	"Salazar Slytherin": ["Slytherin", "Slytherin Seeker Terence Higgs", "Slytherins"],
	"Severus Snape": ["Snape"],
	"Pomona Sprout": ["Sprout"],
	"Bill Weasley": ["Bill", "Bill'", "Bill's"],
	"Charlie Weasley": ["Charlie"],
	"Fred Weasley": ["Fred", "Fred and", "Misters Fred"],
	"George Weasley": ["George"],
	"Ginny Weasley": ["Ginny"],
	"Molly Weasley": ["Mrs. Weasley"],
	"Percy Weasley": ["Mr. Weasley", "Percy", "Percy the Prefect"],
	"Weasley Family": ["Weasleys", "The Weasleys"],
	"Ron Weasley": ["Mr. Ronald Weasley", "Ron", "Ronald", "Ronald Weasley", "Weasley"],
	"Oliver Wood": ["Oliver", "Oliver Wood's"],
	"Blaise Zabini": ["Blaise"],
	"Bloody Baron": ["Baron", "Mr. Baron"],
	"Fat Friar": ["Friar"],
	"Fat Lady": ["The Fat Lady"],
	"Nicholas de Mimsy": ["Nicholas"],
	"Norbert": ["Add Norbert"],
	"Vincent Crabbe": ["Crabbe"],
	"Dedalus Diggle": ["Dedalus Diggle's", "Diggle"],
	"Katie Bell": ["Chaser Bell", "Chaser Katie Bell"],
	"Aberforth Dumbledore": ["Dumbledore", "Trust Dumbledore"],
	"Dudley Dursley": ["Dud ley", "Dudley"],
	"Petunia Dursley": ["Aunt Petunia", "Mrs. Dursley", "Petunia"],
	"Vernon Dursley": ["Mr. Dursley", "Uncle", "Uncle Vernon", "Uncle Vernon's", "Vernon"],
	"Dursleys Family": ["Dursleys", "Dursley's", "The Dursleys", "Mr. and Mrs. Dursley"],
	"Arabella Figg": ["Mrs. Figg"],
	"Argus Filch": ["Filch", "Mr. Filch"],
	"Justin Finch-Fletchley": ["Jus"],
	"Seamus Finnigan": ["Finnigan", "Seamus"],
	"Nicolas Flamel": ["Mr. Flamel", "Mr. Nicolas Flamel", "Nicolas"],
	"Filius Flitwick": ["Flitwick"],
	"Tom Riddle": ["Tom"],
	"Helena Ravenclaw" : [],
	"Rowena Ravenclaw" : [],
	"Mary Riddle" : [],
	"Thomas Riddle" : [],
	"Lord Voldemort" : [],
	"Augustus Rookwood" : [],
	"Newt Scamander" : [],
	"Rufus Scrimgeour" : [],
	"Kingsley Shacklebolt" : [],
	"Charity Burbage" : [],
	"Stan Shunpike" : [],
	"Rita Skeeter" : [],
	"Horace Slughorn" : [],
	"Hepzibah Smith" : [],
	"Zacharias Smith" : [],
	"Alicia Spinnet" : [],
	"Pius Thicknesse" : [],
	"Frank Bryce" : [],
	"Dean Thomas" : [],
	"Andromeda Tonks" : [],
	"Nymphadora Tonks" : [],
	"Ted Tonks" : [],
	"Sybill Trelawney" : [],
	"Dolores Umbridge" : [],
	"Emmeline Vance" : [],
	'Adalbert Waffling' : [],
	"Romilda Vane" : [],
	"Septima Vector" : [],
	"Arthur Weasley" : [],
	"Alecto Carrow" : [],
	"Amycus Carrow" : [],
	"Aragog" : [],
	"Bane" : [],
	"Buckbeak" : [],
	"Sir Cadogan" : [],
	"Crookshanks" : [],
	"Dobby" : [],
	"Fang" : [],
	"Reginald Cattermole" : [],
	"Fawkes" : [],
	"Firenze" : [],
	"Fluffy" : [],
	"Grawp" : [],
	"Griphook" : [],
	"Hedwig" : [],
	"Kreacher" : [],
	"Moaning Myrtle" : [],
	"Mrs. Norris" : [],
	"Nagini" : [],
	"Mary Cattermole" : [],
	"Peeves" : [],
	"Madam Rosmerta" : [],
	"Scabbers" : [],
	"Trevor" : [],
	"Winky" : [],
	"Wormtail" : [],
	"Cho Chang" : [],
	"Penelope Clearwater" : [],
	"Bathilda Bagshot" : [],
	"Michael Corner" : [],
	"Colin Creevey" : [],
	"Dirk Cresswell" : [],
	"Barty Crouch Sr." : [],
	"Barty Crouch Jr." : [],
	"Fleur Delacour" : [],
	"Gabrielle Delacour" : [],
	"Amos Diggory" : [],
	"Cedric Diggory" : [],
	"Elphias Doge" : [],
	"Antonin Dolohov" : [],
	"Albus Dumbledore" : [],
	"Ariana Dumbledore" : [],
	"Kendra Dumbledore" : [],
	"Percival Dumbledore" : [],
	"Cuthbert Binns" : [],
	"Majorie Dursley" : [],
	"Marietta Edgecombe" : [],
	"Everard" : [],
	"Regulus Black" : [],
	"Mundungus Fletcher" : [],
	"Cornelius Fudge" : [],
	"Marvolo Gaunt" : [],
	"Merope Gaune" : [],
	"Morfin Gaunt" : [],
	"Anthony Goldstein" : [],
	"Gregorovitch" : [],
	"Fenrir Greyback" : [],
	"Wilhelmina Grubbly-Plank" : [],
	"Godric Gryffindor" : [],
	"Rolanda Hooch" : [],
	"Amelia Bones" : [],
	"Igor Karkaroff" : [],
	"Viktor Krum" : [],
	"Bellatrix Lestrange" : [],
	"Rabastan Lestrange" : [],
	"Rodolphus Lestrange" : [],
	"Gilderoy Lockhart" : [],
	"Alice Longbottom" : [],
	"Augusta Longbottom" : [],
	"Frank Longbottom" : [],
	"Luna Lovegood" : [],
	"Xenophilius Lovegood" : [],
	"Remus Lupin" : [],
	"Teddy Lupin": ["Ted"],
	"Lucius Malfoy" : [],
	"Narcissa Malfoy" : [],
	"Olympe Maxime" : [],
	"Ernie Macmillan" : [],
	"Cormac McLaggen" : [],
	"Alaster Moody" : [],
	"Theodore Nott" : [],
	"Bob Ogden" : [],
	"Tiberius Ogden" : [],
	"Pansy Parkinson" : [],
	"Padma Patil" : [],
	"Parvati Patil" : [],
	"Peter Pettigrew" : [],    
	'Crikey' : [],
	"Doris Crockford" : [],
	"Gordon" : [],
	"Harold" : [],
	"Malcolm" : [],
	"Marcus Flint" : [],
	"Morgana" : [],
	'Quentin Trimble' : [],
  	"Ludo Bagman": [],
	"Lavender Brown": [],
	"Antioch Peverell": [],
	"Cadmus Peverell": [],
	"Ignotus Peverell": [],
	"Sturgis Podmore": [],
}
