# Not detected by the NER

patterns = [
    {"label": "PERSON", "pattern": "Professor McGonagall"},
    {"label": "PERSON", "pattern": "Uncle Vernon"},
    {"label": "PERSON", "pattern": "Uncle Vernon's"},
    {"label": "PERSON", "pattern": "Aunt Petunia"},
    {"label": "PERSON", "pattern": "Vernon"},
    {"label": "PERSON", "pattern": "Dudley's"},
    {"label": "PERSON", "pattern": "Auntie Marge's"},
    {"label": "PERSON", "pattern": "the Potters"},
    {"label": "PERSON", "pattern": "Grindelwald"},
    {"label": "PERSON", "pattern": "Bulstrode Millicent"},
    {"label": "PERSON", "pattern": "Zabini Blaise"}
]

# ---
# Proper nouns cleaning

# Credits to Martin, D. P.
# From http://dpmartin42.github.io/posts/wizard-network
all_real_names = {
	"Hannah_Abbott": ["Abbott", "Hannah"],
	"Irma_Pince": ["Pince"],
	"Poppy_Pomfrey": ["Pomfrey", "Pomftey"],
	"James_Potter": ["James", "Mr. Potter"],
	"Lily_Potter": ["Lily", "Lily an'", "Mrs. Potter"],
	"Harry_Potter": ["Harry", "Potter", "Happy Birthday Harry", "Mr. H. Potter", "Mr. Harry Potter", "The Harry Potter"],
	"Quirinus_Quirrell": ["Quirrell", "Quirtell"],
	"Millicent_Bulstrode": ["Bulstrode", "Bulstrode Millicent", "Millicent"],
	"Gregory_Goyle": ["Goyle"],
	"Hermione_Granger": ["Gran", "Granger", "Hermione", "Hermlone", "Miss Granger", "Miss Granger's"],
	"Sirius_Black": ["Sirius"],
	"Gellert_Grindelwald": ["Grindelwald"],
	"Rubeus_Hagrid": ["Hagrid"],
	"Helga_Hufflepuff": ["Hufflepuff", "Hufflepuffis"],
	"Angelina_Johnson": ["Angelina", "Chaser Angelina Johnson", "Johnson"],
	"Lee_Jordan": ["Jordan", "Lee", "Lee Jordan's"],
	"Neville_Longbottom": ["Mr. Longbottom", "Mr. Neville Longbottom", "Neville"],
	"Susan_Bones": ["Susan"],
	"Draco_Malfoy": ["Malfoy", "Mr. Malfoy"],
	"Minerva_McGonagall": ["McGonagall", "McGonagall Harry", "Professor McGonagall"],
	#"Terry_Boot": ["Terry"],
	"Garrick_Ollivander": ["Mr. Ollivander"],
	"Bettie_Bott": ["Bettie", "Bettie Bott's"],
	"Malfoys_Family": ["Malfoys", "The Malfoys"],
	"Auntie_Marge": ["Marge"],
	"Piers_Polkiss": ["Piers"],
	"Potter_Family": ["Potters", "the Potters", "The Potters"],
	"Salazar_Slytherin": ["Slytherin", "Slytherin Seeker Terence Higgs", "Slytherins"],
	"Severus_Snape": ["Snape"],
	#"Pomona_Sprout": ["Sprout"],
	"Bill_Weasley": ["Bill", "Bill'", "Bill's"],
	"Charlie_Weasley": ["Charlie"],
	"Fred_Weasley": ["Fred", "Fred and", "Misters Fred"],
	"George_Weasley": ["George"],
	"Ginny_Weasley": ["Ginny"],
	"Molly_Weasley": ["Mrs. Weasley"],
	"Percy_Weasley": ["Mr. Weasley", "Percy", "Percy the Prefect"],
	"Weasley_Family": ["Weasleys", "The Weasleys"],
	"Ron_Weasley": ["Mr. Ronald Weasley", "Ron", "Ronald", "Ronald Weasley", "Weasley"],
	"Oliver_Wood": ["Oliver", "Oliver Wood's"],
	"Blaise_Zabini": ["Blaise", "Zabini", "Zabini Blaise"],
	#"Bloody_Baron": ["Baron", "Mr. Baron"],
	#"Fat_Friar": ["Friar"],
	"Fat_Lady": ["The Fat Lady"],
	"Nicholas_de_Mimsy": ["Nicholas"],
	"Norbert": ["Add Norbert"],
	"Vincent_Crabbe": ["Crabbe"],
	"Dedalus_Diggle": ["Dedalus Diggle's", "Diggle"],
	"Katie_Bell": ["Chaser Bell", "Chaser Katie Bell"],
	"Dudley_Dursley": ["Dud ley", "Dudley"],
	"Petunia_Dursley": ["Aunt Petunia", "Mrs. Dursley", "Petunia"],
	"Vernon_Dursley": ["Mr. Dursley", "Uncle", "Uncle Vernon", "Uncle Vernon's", "Vernon"],
	"Dursleys_Family": ["Dursleys", "Dursley's", "The Dursleys", "Mr. and Mrs. Dursley"],
	"Arabella_Figg": ["Mrs. Figg"],
	"Argus_Filch": ["Filch", "Mr. Filch"],
	"Justin_Finch": ["Jus", "Justin"],
	"Seamus_Finnigan": ["Finnigan", "Seamus"],
	"Nicolas_Flamel": ["Mr. Flamel", "Mr. Nicolas Flamel", "Nicolas", "Nicolas Flamel"],
	"Filius_Flitwick": ["Flitwick"],
	"Tom_Riddle": ["Tom"],
	"Helena_Ravenclaw" : [],
	"Rowena_Ravenclaw" : [],
	"Mary_Riddle" : [],
	"Thomas_Riddle" : [],
	"Lord_Voldemort" : [],
	"Augustus_Rookwood" : [],
	"Newt_Scamander" : [],
	"Rufus_Scrimgeour" : [],
	"Kingsley_Shacklebolt" : [],
	"Charity_Burbage" : [],
	"Stan_Shunpike" : [],
	"Rita_Skeeter" : [],
	"Horace_Slughorn" : [],
	"Hepzibah_Smith" : [],
	"Zacharias_Smith" : [],
	"Alicia_Spinnet" : [],
	"Pius_Thicknesse" : [],
	"Frank_Bryce" : [],
	"Dean_Thomas" : [],
	"Andromeda_Tonks" : [],
	"Nymphadora_Tonks" : [],
	"Ted_Tonks" : [],
	"Sybill_Trelawney" : [],
	"Dolores_Umbridge" : [],
	"Emmeline_Vance" : [],
	'Adalbert_Waffling' : [],
	"Romilda_Vane" : [],
	"Septima_Vector" : [],
	"Arthur_Weasley" : [],
	"Alecto_Carrow" : [],
	"Amycus_Carrow" : [],
	"Aragog" : [],
	"Bane" : [],
	"Buckbeak" : [],
	"Sir_Cadogan" : [],
	"Crookshanks" : [],
	"Dobby" : [],
	#"Fang" : [],
	"Reginald_Cattermole" : [],
	"Fawkes" : [],
	"Firenze" : [],
	"Fluffy" : [],
	"Grawp" : [],
	"Griphook" : [],
	"Hedwig" : [],
	"Kreacher" : [],
	"Moaning_Myrtle" : [],
	"Norris" : ["Mrs. Norris"],
	"Nagini" : [],
	"Mary_Cattermole" : [],
	"Peeves" : [],
	"Madam_Rosmerta" : [],
	"Scabbers" : [],
	#"Trevor" : [],
	"Winky" : [],
	"Wormtail" : [],
	"Cho_Chang" : [],
	"Penelope_Clearwater" : [],
	"Bathilda_Bagshot" : [],
	"Michael_Corner" : [],
	"Colin_Creevey" : [],
	"Dirk_Cresswell" : [],
	"Barty_Crouch_Sr." : [],
	"Barty_Crouch_Jr." : [],
	"Fleur_Delacour" : [],
	"Gabrielle_Delacour" : [],
	"Amos_Diggory" : [],
	"Cedric_Diggory" : [],
	"Elphias_Doge" : [],
	"Antonin_Dolohov" : [],
	"Albus_Dumbledore": ["Dumbledore", "Trust Dumbledore", "Albus"],
  	"Aberforth_Dumbledore": [],
	"Ariana_Dumbledore" : [],
	"Kendra_Dumbledore" : [],
	"Percival_Dumbledore" : [],
	"Cuthbert_Binns" : [],
	"Majorie_Dursley" : [],
	"Marietta_Edgecombe" : [],
	"Everard" : [],
	"Regulus_Black" : [],
	"Mundungus_Fletcher" : [],
	#"Cornelius_Fudge" : [],
	"Marvolo_Gaunt" : [],
	"Merope_Gaune" : [],
	"Morfin_Gaunt" : [],
	"Anthony_Goldstein" : [],
	"Gregorovitch" : [],
	"Fenrir_Greyback" : [],
	"Wilhelmina_Grubbly-Plank" : [],
	"Godric_Gryffindor" : [],
	"Rolanda_Hooch" : [],
	"Amelia_Bones" : [],
	"Igor_Karkaroff" : [],
	"Viktor_Krum" : [],
	"Bellatrix_Lestrange" : [],
	"Rabastan_Lestrange" : [],
	"Rodolphus_Lestrange" : [],
	"Gilderoy_Lockhart" : [],
	"Alice_Longbottom" : [],
	"Augusta_Longbottom" : [],
	"Frank_Longbottom" : [],
	"Luna_Lovegood" : [],
	"Xenophilius_Lovegood" : [],
	"Remus_Lupin" : [],
	#"Teddy_Lupin": ["Ted"],
	"Lucius_Malfoy" : [],
	"Narcissa_Malfoy" : [],
	"Olympe_Maxime" : [],
	"Ernie_Macmillan" : [],
	"Cormac_McLaggen" : [],
	"Alaster_Moody" : [],
	"Theodore_Nott" : [],
	"Bob_Ogden" : [],
	"Tiberius_Ogden" : [],
	#"Pansy_Parkinson" : [],
	"Padma_Patil" : [],
	"Parvati_Patil" : [],
	"Peter_Pettigrew" : [],    
	'Crikey' : [],
	"Doris_Crockford" : [],
	"Gordon" : [],
	#"Harold" : [],
	"Malcolm" : [],
	"Marcus_Flint" : [],
	#"Morgana" : [],
	'Quentin_Trimble' : [],
  	"Ludo_Bagman": [],
	"Lavender_Brown": [],
	"Antioch_Peverell": [],
	"Cadmus_Peverell": [],
	"Ignotus_Peverell": [],
	"Sturgis_Podmore": [],
}
