# Not detected by the NER

patterns = [
    {"label": "PERSON", "pattern": "Professor McGonagall"},
    {"label": "PERSON", "pattern": "Uncle Vernon"},
    {"label": "PERSON", "pattern": "Uncle Vernon's"},
    {"label": "PERSON", "pattern": "Aunt Petunia"},
    {"label": "PERSON", "pattern": "Vernon"},
    {"label": "PERSON", "pattern": "Dudley's"},
    {"label": "PERSON", "pattern": "Auntie Marge's"},
]

# ---
# Proper nouns cleaning

# Credits to Martin, D. P.
# From http://dpmartin42.github.io/posts/wizard-network
persons_real_names = [
	"Hannah Abbott",
	"Ludo Bagman",
	"Lavender Brown",
	"Antioch Peverell",
	"Cadmus Peverell",
	"Ignotus Peverell",
	"Irma Pince",
	"Sturgis Podmore",
	"Poppy Pomfrey",
	"Harry Potter",
	"James Potter",
	"Lily Potter",
	"Quirinus Quirrell",
	"Millicent Bulstrode",
	"Helena Ravenclaw",
	"Rowena Ravenclaw",
	"Mary Riddle",
	"Thomas Riddle",
	"Tom Riddle",
	"Lord Voldemort",
	"Augustus Rookwood",
	"Newt Scamander",
	"Rufus Scrimgeour",
	"Kingsley Shacklebolt",
	"Charity Burbage",
	"Stan Shunpike",
	"Rita Skeeter",
	"Horace Slughorn",
	"Salazar Slytherin",
	"Hepzibah Smith",
	"Zacharias Smith",
	"Severus Snape",
	"Alicia Spinnet",
	"Pomona Sprout",
	"Pius Thicknesse",
	"Frank Bryce",
	"Dean Thomas",
	"Andromeda Tonks",
	"Nymphadora Tonks",
	"Ted Tonks",
	"Sybill Trelawney",
	"Dolores Umbridge",
	"Emmeline Vance",
	'Adalbert Waffling',
	"Romilda Vane",
	"Septima Vector",
	"Arthur Weasley",
	"Alecto Carrow",
	"Bill Weasley",
	"Charlie Weasley",
	"Fred Weasley",
	"George Weasley",
	"Ginny Weasley",
	"Molly Weasley",
	"Percy Weasley",
	"Weasley Family",
	"Ron Weasley",
	"Oliver Wood",
	"Blaise Zabini",
	"Amycus Carrow",
	"Aragog",
	"Bane",
	"Bloody Baron",
	"Buckbeak",
	"Sir Cadogan",
	"Crookshanks",
	"Dobby",
	"Fang",
	"Fat Friar",
	"Fat Lady",
	"Reginald Cattermole",
	"Fawkes",
	"Firenze",
	"Fluffy",
	"Grawp",
	"Griphook",
	"Hedwig",
	"Kreacher",
	"Moaning Myrtle",
	"Mrs. Norris",
	"Nagini",
	"Mary Cattermole",
	"Nicholas de Mimsy",
	"Norbert",
	"Peeves",
	"Madam Rosmerta",
	"Scabbers",
	"Trevor",
	"Winky",
	"Wormtail",
	"Cho Chang",
	"Penelope Clearwater",
	"Bathilda Bagshot",
	"Michael Corner",
	"Vincent Crabbe",
	"Colin Creevey",
	"Dirk Cresswell",
	"Barty Crouch Sr.",
	"Barty Crouch Jr.",
	"Fleur Delacour",
	"Gabrielle Delacour",
	"Dedalus Diggle",
	"Katie Bell",
	"Amos Diggory",
	"Cedric Diggory",
	"Elphias Doge",
	"Antonin Dolohov",
	"Aberforth Dumbledore",
	"Albus Dumbledore",
	"Ariana Dumbledore",
	"Kendra Dumbledore",
	"Percival Dumbledore",
	"Dudley Dursley",
	"Cuthbert Binns",
	"Majorie Dursley",
	"Petunia Dursley",
	"Vernon Dursley",
	"Dursleys Family",
	"Marietta Edgecombe",
	"Everard",
	"Arabella Figg",
	"Argus Filch",
	"Justin Finch-Fletchley",
	"Seamus Finnigan",
	"Nicolas Flamel",
	"Regulus Black",
	"Mundungus Fletcher",
	"Filius Flitwick",
	"Cornelius Fudge",
	"Marvolo Gaunt",
	"Merope Gaune",
	"Morfin Gaunt",
	"Anthony Goldstein",
	"Gregory Goyle",
	"Hermione Granger",
	"Sirius Black",
	"Gregorovitch",
	"Fenrir Greyback",
	"Gellert Grindelwald",
	"Wilhelmina Grubbly-Plank",
	"Godric Gryffindor",
	"Rubeus Hagrid",
	"Rolanda Hooch",
	"Helga Hufflepuff",
	"Angelina Johnson",
	"Lee Jordan",
	"Amelia Bones",
	"Igor Karkaroff",
	"Viktor Krum",
	"Bellatrix Lestrange",
	"Rabastan Lestrange",
	"Rodolphus Lestrange",
	"Gilderoy Lockhart",
	"Alice Longbottom",
	"Augusta Longbottom",
	"Frank Longbottom",
	"Neville Longbottom",
	"Susan Bones",
	"Luna Lovegood",
	"Xenophilius Lovegood",
	"Remus Lupin",
	"Teddy Lupin",
	"Draco Malfoy",
	"Lucius Malfoy",
	"Narcissa Malfoy",
	"Olympe Maxime",
	"Ernie Macmillan",
	"Minerva McGonagall",
	"Terry Boot",
	"Cormac McLaggen",
	"Alaster Moody",
	"Theodore Nott",
	"Bob Ogden",
	"Tiberius Ogden",
	"Garrick Ollivander",
	"Pansy Parkinson",
	"Padma Patil",
	"Parvati Patil",
	"Peter Pettigrew",
	"Bettie Bott",
    'Crikey',
	"Doris Crockford",
	"Gordon",
	"Harold",
	"Malcolm",
	"Malfoy Family",
	"Marcus Flint",
	"Auntie Marge",
	"Morgana",
	"Piers Polkiss",
	"Potter Family",
	'Quentin Trimble',
]

name_to_replace = {
    "Abbott": "Hannah Abbott",
   	'Add Norbert': "Norbert",
   	'Angelina': "Angelina Johnson",
   	'Aunt Petunia': "Petunia Dursley",
   	'Baron': "Bloody Baron",
   	"Bettie Bott's": "Bettie Bott",
   	'Bill': "Bill Weasley",
   	"Bill's": "Bill Weasley",
   	'Blaise': "Blaise Zabini",
   	'Bulstrode': "Millicent Bulstrode",
   	'Charlie': "Charlie Weasley",
   	'Chaser Angelina Johnson': "Angelina Johnson",
   	'Chaser Bell': "Katie Bell",
   	'Chaser Katie Bell': "Katie Bell",
   	'Crabbe': "Vincent Crabbe",
   	"Dedalus Diggle's": "Dedalus Diggle",
   	'Diggle': "Dedalus Diggle",
   	'Dud ley': "Dudley Dursley",
   	'Dudley': "Dudley Dursley",
   	'Dumbledore': "Albus Dumbledore",
   	'Dursley': "Dudley Dursley",
   	'Dursleys': "Dursley Family",
   	'Filch': "Argus Filch",
   	'Finnigan': "Seamus Finnigan",
   	'Flitwick': "Filius Flitwick",
   	'Fred': "Fred Weasley",
   	'Fred and': "Fred Weasley",
   	'Friar': "Fat Friar",
   	'George': "George Weasley",
   	'Ginny': "Ginny Weasley",
   	'Goyle': "Gregory Goyle",
   	'Gran': "Hermione Granger",
   	'Granger': "Hermione Granger",
   	'Grindelwald': "Gellert Grindelwald",
   	'Hagrid': "Rubeus Hagrid",
   	'Hannah': "Hannah Abbott",
   	'Happy Birthday Harry': "Harry Potter",
   	'Harry': "Harry Potter",
   	'Hermione': "Hermione Granger",
   	'Hermlone': "Hermione Granger",
   	'Hufflepuff': "Helga Hufflepuff",
   	'Hufflepuffis': "Helga Hufflepuff",
   	'James': "James Potter",
   	'Johnson': "Angelina Johnson",
   	'Jordan': "Lee Jordan",
   	'Jus': "Justin Finch-Fletchley",
   	'Lee': "Lee Jordan",
   	"Lee Jordan's": "Lee Jordan",
   	'Lily': "Lily Potter",
   	"Lily an'": "Lily Potter",
   	'Malfoy': "Draco Malfoy",
   	'Malfoys': "Malfoy Family",
   	'Marge': "Auntie Marge",
   	'McGonagall': "Minerva McGonagall",
   	'McGonagall Harry': "Minerva McGonagall",
   	'Miss Granger': "Hermione Granger",
   	"Miss Granger's": "Hermione Granger",
   	'Misters Fred': "Fred Weasley",
   	'Mr. Baron': "Bloody Baron",
   	'Mr. Dursley': "Vernon Dursley",
   	'Mr. Filch': "Argus Filch",
   	'Mr. Flamel': "Nicolas Flamel",
   	'Mr. H. Potter': "Harry Potter",
   	'Mr. Harry Potter': "Harry Potter",
   	'Mr. Longbottom': "Neville Longbottom",
   	'Mr. Malfoy': "Draco Malfoy",
   	'Mr. Neville Longbottom':  "Neville Longbottom",
   	'Mr. Nicolas Flamel': "Nicolas Flamel",
   	'Mr. Ollivander': "Garrick Ollivander",
   	'Mr. Potter': "Harry Potter",
   	'Mr. Ronald Weasley': "Ron Weasley",
   	'Mr. Weasley': "Ron Weasley",
   	'Mrs. Dursley': "Petunia Dursley",
   	'Mrs. Figg': "Arabella Figg",
   	'Mrs. Potter': "Lily Potter",
   	'Mrs. Weasley': "Molly Weasley",
   	'Neville': "Neville Longbottom",
   	'Nicholas': "Nicholas de Mimsy",
   	'Nicolas': "Nicolas Flamel",
   	"Nicolas Flamel'": "Nicolas Flamel",
   	'Oliver': "Oliver Wood",
   	"Oliver Wood's": "Oliver Wood",
   	'Percy': "Percy Weasley",
   	'Percy the Prefect': "Percy Weasley",
   	'Petunia': "Petunia Dursley",
   	'Piers': "Piers Polkiss",
   	'Pince': "Irma Pince",
   	'Pomfrey': "Poppy Pomfrey",
   	'Pomftey': "Poppy Pomfrey",
   	'Potter': "Harry Potter",
   	'Potters': "Potter Family",
   	'Professor McGonagall': "Minerva McGonagall",
   	'Quirrell': "Quirinus Quirrell",
   	'Quirtell': "Quirinus Quirrell",
   	'Ron': "Ron Weasley",
   	'Ronald Weasley': "Ron Weasley",
   	'Seamus': "Seamus Finnigan",
   	'Sirius': "Sirius Black",
   	'Slytherin': "Salazar Slytherin",
   	'Slytherin Seeker Terence Higgs': "Salazar Slytherin",
   	'Slytherins': "Salazar Slytherin",
   	'Snape': "Severus Snape",
   	'Sprout': "Pomona Sprout",
   	'Susan': "Susan Bones",
   	'Ted': "Teddy Lupin",
   	'Terry': "Terry Boot",
   	'The Fat Lady': "Fat Lady",
   	'The Harry Potter': "Harry Potter",
   	'Tom': "Tom Riddle",
   	'Trust Dumbledore': "Albus Dumbledore",
   	'Uncle': "Vernon Dursley",
   	'Uncle Vernon': "Vernon Dursley",
   	"Uncle Vernon's": "Vernon Dursley",
   	'Vernon': "Vernon Dursley",
   	'Weasley': "Ron Weasley",
   	'Weasleys': "Weasley Family"
}
